stages:
  - build
  - test
  - confidence-check

build:
  stage: build
  script:
    - mkdir -p code/test/test_results
  artifacts:
    paths:
      - code/test/test_results/

unit test:
  stage: test
  image: python:3.7
  script:
    - echo "Testing"
    - pip install -r requirments.txt
    - pip install pytest
    - pip install webdriver-manager
    - pwd
    - cd code/test/
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - py.test --junitxml test_results/results.xml test_models.py -v
  artifacts:
    reports:
      junit: code/test/test_results/results.xml

e2e:chrome:
  stage: test
  image: python:3.7
  script:
    - pwd
    - ls -l /builds/dosehunter/testingmandatory2_exam/
    - pip install pytest
    - pip install selenium
    - pip install pytest-selenium
    - wget -q -O — https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo ‘deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main’ | tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
#    - pytest code/test/test_app.py
    - pytest -vvv --driver Remote --capability browserName chrome --host selenium --port 4444 code/test/test_app.py
  services:
    - name: selenium/standalone-chrome
      alias: selenium

#e2e:firefox:
#  stage: confidence-check
#  services:
#    - selenium/standalone-firefox
#  script:
#    - npm run confidence-check --host=selenium__standalone-firefox
