stages:
    - build
    - test

build:
    stage: build
    script:
        - mkdir -p code/test/test_results
    artifacts:
        paths:
            - code/test/test_results/

test:
    stage: test
    image: python:3.7
    script:
        - echo "Testing"
        - pip install -r requirments.txt
        - pip install pytest
        - pip install webdriver-manager
        - pwd
        - cd code/test/
        - ls -l
        - export PYTHONPATH="$PYTHONPATH:."
        - python -c "import sys;print(sys.path)"
        - py.test --junitxml test_results/results.xml test_models.py -v
    artifacts:
        reports:
            junit: test_results/results.xml
